name: CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [ '2.4', '2.5', '2.6', '2.7' ]
        gemfile:
          - .gemfiles/rails-5.0.x.gemfile
          - .gemfiles/rails-5.1.x.gemfile
          - .gemfiles/rails-5.2.x.gemfile
          - .gemfiles/rails-6.0.x.gemfile
          - .gemfiles/rails-6.1.x.gemfile
        exclude:
          - ruby: '2.4'
            gemfile: .gemfiles/rails-6.0.x.gemfile
          - ruby: '2.4'
            gemfile: .gemfiles/rails-6.1.x.gemfile

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install dependencies
        run: bundle install --gemfile=${{ matrix.gemfile }} --jobs 4
      - name: Run tests
        run: bundle exec rake
